const data = {
  products: [
    {
      id: 1,
      qty:1,
      name: "Free Shirt",
      slug: "free-shirt",
      category: "Shirts",
      image: "/images/shirt1.jpg",
      price: 20000,
      brand: "Block Boi",
      rating: {rate : 4.5, count : 100},
      countInStock: 20,
      description: " A classic button-up shirt made from high-quality cotton, featuring a tailored fit and a pointed collar. Versatile and timeless, it can be dressed up with a blazer or worn casually with jeans.",
    },
    {
      id: 2,
      qty:1,
      name: "Fit Shirt",
      slug: "fit-shirt",
      category: "Shirts",
      image: "/images/shirt2.jpg",
      price: 15000,
      brand: "Block Boi",
      rating: {rate : 4.5, count : 110},
      countInStock:18,
      description: "A wardrobe essential, this polo shirt is made from breathable fabric and features a collared neckline and short sleeves. It strikes the right balance between casual and smart, making it suitable for various outings.",
    },
    {
      id: 3,
      qty:1,
      name: "Slim Shirt",
      slug: "slim-shirt",
      category: "Shirts",
      image: "/images/shirt3.jpg",
      price: 10000,
      brand: "Block Boi",
      rating: {rate : 4.5, count : 120},
      countInStock:18,
      description: "A versatile and cozy sweater with a V-shaped neckline, perfect for layering or wearing on its own. Made from soft and warm materials like wool or cashmere, it adds both style and comfort to any outfit.",
    },
    {
      id: 4,
      qty:1,
      name: "Golf Pants",
      slug: "golf-pants",
      category: "Pants",
      image: "/images/pants1.jpg",
      price: 40000,
      brand: "Block Boi",
      rating: {rate : 4.5, count : 130},
      countInStock:15,
      description: "Designed for both style and functionality, these shorts feature multiple pockets for carrying essentials. Made from durable fabric, they are perfect for casual outings or outdoor activities during warmer months.",
    },
    {
      id: 5,
      qty:1,
      name: "Fit Pants",
      slug: "fit-pants",
      category: "Pants",
      image: "/images/pants2.jpg",
      price: 30000,
      brand: "Block Boi",
      rating: {rate : 4.5, count : 140},
      countInStock:25,
      description: " A rugged and edgy choice, these jeans feature a distressed finish, adding a touch of personality and character to any outfit. Pair them with a t-shirt and sneakers for a cool and laid-back look",
    },
    {
      id: 6,
      qty:1,
      name: "Classic Pants",
      slug: "classic-pants",
      category: "Pants",
      image: "/images/pants3.jpg",
      price: 80000,
      brand: "Block Boi",
      rating: {rate : 4.8, count : 150},
      countInStock:35,
      description: "Add a pop of personality to your outfit with patterned socks. From stripes to polka dots to bold designs, they allow you to showcase your individuality and sense of style, even in more formal settings.",
    },
    {
      id: 7,
      qty:1,
      name: "Classic Pants",
      slug: "classic-pants",
      category: "Pants",
      image: "/images/pants3.jpg",
      price: 80000,
      brand: "Block Boi",
      rating: {rate : 4.8, count : 160},
      countInStock:35,
      description: "Add a pop of personality to your outfit with patterned socks. From stripes to polka dots to bold designs, they allow you to showcase your individuality and sense of style, even in more formal settings.",
    },
    {
      id: 8,
      qty:1,
      name: "Classic Pants",
      slug: "classic-pants",
      category: "Pants",
      image: "/images/pants3.jpg",
      price: 80000,
      brand: "Block Boi",
      rating: {rate : 3.0, count : 170},
      countInStock:35,
      description: "Designed for both style and functionality, these shorts feature multiple pockets for carrying essentials. Made from durable fabric, they are perfect for casual outings or outdoor activities during warmer months.",
    },
  ],
};

export default data
